# Generated by Django 5.0.1 on 2024-01-30 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertable',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
