# Generated by Django 5.0.1 on 2024-01-30 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0002_usertable_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertable',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
